version: "3.8"

services:
  codepush_server_api:
    build: ./api
    image: codepush-server/api:${BE_VERSION}
    container_name: codepush_server_api
    restart: unless-stopped
    ports:
      - "${SERVER_API_PORT}:${SERVER_API_PORT}"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      SERVER_API_PORT: ${SERVER_API_PORT}
    networks:
      - development

  codepush_server_fe:
    image: codepush-server/fe:${FE_VERSION}
    container_name: codepush_server_fe
    restart: unless-stopped
    build: ./frontend
    ports:
      - "${SERVER_FE_PORT}:${SERVER_FE_PORT}"
    networks:
      - development


networks:
  development:
    name: development
    driver: bridge
