version: "3.8"

services:
  # postgres:
  #   image: postgres:latest
  #   container_name: codepush_postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: codepush
  #     POSTGRES_PASSWORD: securepassword
  #     POSTGRES_DB: codepushdb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  # minio:
  #   image: minio/minio
  #   container_name: codepush_minio
  #   restart: always
  #   environment:
  #     MINIO_ROOT_USER: admin
  #     MINIO_ROOT_PASSWORD: admin123
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   volumes:
  #     - miniodata:/data
  #   command: server /data --console-address ":9001"

  codepush-server:
    build: .
    container_name: codepush_server
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      SERVER_PORT: ${SERVER_PORT}

volumes:
  pgdata:
  miniodata:
